apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sEnforceNonRootReadonly
metadata:
  name: enforce-non-root-readonly-in-audit-zone
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone
