apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:stable
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:stable
      volumeMounts:
        - name: host-logs
          mountPath: /host-logs
  volumes:
    - name: host-logs
      hostPath:
        path: /var/log
        type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:stable
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
